### ISSUE TITLE
Visualization run into mislabel issue when slice the original data by height/width

### ISSUE THREAD

**Issue by susiefeng** [phildong/minian#9] opened 2019-02-04 18:01 UTC
For example, in the last step of visualization after CNMF, my video has been sliced half by height. Then the dots which indicate cells are not at where they supposed to be anymore.
![v_error2](https://user-images.githubusercontent.com/47085209/52227220-edab6800-287c-11e9-957b-5636abf37a49.PNG)

**Comment by susiefeng** [comment] 2019-02-05 14:58
![screen shot 2019-02-05 at 9 58 30 am](https://user-images.githubusercontent.com/47085209/52281692-a1b7fc00-292c-11e9-9d2e-401b40f4ff6d.png)

**Comment by phildong** [comment] 2019-02-05 15:42
cannot reproduce on my end. at least the VArrayViewer works fine after this. Does other visualization work? Can you check the `A.sizes` and see if it has the correct size?

**Comment by phildong** [comment] 2019-02-05 18:21
should be fixed by 659b96ac2b6db6cc4c3ac3679ed270f4d5389d25 feel free to reopen if it's still wrong

**Closed by phildong** 2019-02-05 18:21 UTC
